services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "aichat"
      MYSQL_ROOT_PASSWORD: "secret123"
      SERVICE_NAME: mysql
  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    tty: true
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=mysql