services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: app/php-8.1-fpm:alpine
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /app
    volumes:
      - app-volume:/app
    networks:
      - app-network
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    working_dir: /app
    depends_on:
      - app
    volumes:
      - app-volume:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: "aichat"
      MYSQL_ROOT_PASSWORD: "secret123"
      SERVICE_NAME: mysql
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    tty: true
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app-volume:
    driver: local
